config/routes.rb
Rails.application.routes.draw do
  
  get 'attendances/index'
  get 'users/show'

  devise_for :users
  root to: 'events#index'


  resources :users do
    resources :avatars, only:[:create]
  end

  resources :events do
    resources :pictures, only:[:create]
  end

  
  resources :charges
  resources :attendances

  post 'create_attendance' => 'attendances#create', as: :create_attendance

 namespace :gods do
  get 'index'
  resources :users
  resources :events
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send 
	has_many :attendances
	has_many :events, through: :attendances

	# On crée une méthode qui appele la méthode welcome_email de UserMailer,
	# on passe en paramètre la classe user.
	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/gods/users_controller.rb
class Gods::UsersController < ApplicationController

	def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id]) 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password], description: params[:description])
    @user.save
    redirect_to gods_index_path
    flash[:success] = "The user has been created"
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
      redirect_to gods_users_path
      flash[:success] = "The user has been updated"
    else
      flash[:alert] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to gods_users_path
    flash[:success] = "The user has been deleted"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

  def show
  	dont_show
  	@user = User.find(params[:id])
  end

  def dont_show
  	@user = User.find(params[:id])
  	if @user != current_user
  		redirect_to root_path
  		flash[:alert] = "Condidential Information"
  	end
  end

  def edit
  	@user = User.find(params[:id])
  	redirect_to root_path, notice: "You can't edit this profile ma biche" unless current_user == @user
  end

  def update
  	@user = User.find(params[:id])
  	if current_user == @user
  		if @user.update(description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
  			redirect_to user_path 
  			flash[:success] = "Your profile has been successfully edited"
  		else 
  			flash[:alert] = "Try again"
  			render :edit
  		end
  	else
  		redirect_to root_path, notice: "You can't edit this profile ma biche"
  	end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit-form.html.erb
<%= form_tag url_for(action: 'update'), method: "patch", class: "mt-4" do %>

  <!-- First name -->
  <div class="form-group">
  <b><%= label_tag 'First Name' %></b>
  <%= text_field_tag 'first_name', @user.first_name, class: "form-control"  %>
  </div>

  <!-- Last name -->
  <div class="form-group">
  <b><%= label_tag 'Last Name' %></b>
  <%= text_field_tag 'last_name', @user.last_name, class: "form-control"  %>
  </div>

  <!-- Description -->
  <div class="form-group">
  <b><%= label_tag 'Description' %></b>
  <%= text_area_tag 'description', @user.description, class: "form-control" %>
  </div>

  <!-- Submit button -->
  <%= submit_tag "Edit", class: "btn btn-primary" %>

<% end %>    

app/views/users/_edit_user_form.html.erb
<%= form_tag url_for(action: 'update'), method: "patch", class: "mt-4" do %>

  <!-- First name -->
  <div class="form-group">
  <b><%= label_tag 'First Name' %></b>
  <%= text_field_tag 'first_name', @user.first_name, class: "form-control"  %>
  </div>

  <!-- Last name -->
  <div class="form-group">
  <b><%= label_tag 'Last Name' %></b>
  <%= text_field_tag 'last_name', @user.last_name, class: "form-control"  %>
  </div>

  <!-- Description -->
  <div class="form-group">
  <b><%= label_tag 'Description' %></b>
  <%= text_area_tag 'description', @user.description, class: "form-control" %>
  </div>

  <!-- Submit button -->
  <%= submit_tag "Edit", class: "btn btn-primary" %>

<% end %>    

app/views/users/_test.html.erb
<p>
	Le resultat du test : <br>
	<%= test_var %>
</p>

app/views/users/_user_avatar_zone.html.erb
<div class="row">
	<div class="col text-center my-4">
		<% if @user.avatar.attached? == true %>
<%= image_tag @user.avatar, alt: 'avatar', style: 'width:200px; height:auto;', class: 'mx-auto' %>
<% end %>
	</div>
</div>
<div class="row">
	<div class="col text-center mb-4">
<%= form_tag user_avatars_path(@user), multipart: true, class: "btn btn-sm" do %>
 <%= file_field_tag :avatar %>
 <%= submit_tag "Upload", class: "btn btn-primary btn-sm mt-2" %>
<% end %>
</div>
</div>

app/views/users/_user_card.html.erb
<div class="row">
	<div class="col col-8 mx-auto mb-4">
		<div class="card border-secondary">
			<div class="card-header">Profile</div>
			<div class="card-body">
				<h4 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h4>
				<small><%= @user.email %></small>
				<p class="card-text"><%= @user.description %></p>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col col-8 mx-auto text-center mb-4">
		<%= link_to "Edit account information", edit_user_registration_path, class: "btn btn-primary btn-sm" %>
		<%= link_to "Edit personal information", edit_user_path, class: "btn btn-primary btn-sm ml-3" %>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container mt-4">
	<div class="row">
		<div class="col col-8 mx-auto">
			<h2>Edit your personal information</h2>

			<%= render 'edit_user_form' %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">

			<%= render 'user_avatar_zone.html.erb' %>
			<%= render 'user_card.html.erb' %>

<%= render partial: 'shared/events_cards', locals: {events: Event.where(admin_id: @user.id)}%>
</div>