config/routes.rb
Rails.application.routes.draw do
  
  get 'attendances/index'
  get 'users/show'

  devise_for :users
  root to: 'events#index'


  resources :users do
    resources :avatars, only:[:create]
  end

  resources :events do
    resources :pictures, only:[:create]
  end

  
  resources :charges
  resources :attendances

  post 'create_attendance' => 'attendances#create', as: :create_attendance

 namespace :gods do
  get 'index'
  resources :users
  resources :events
  end
end

app/models/event.rb
class Event < ApplicationRecord

	has_one_attached :picture
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :admin, class_name: "User"

	# --------------- Validates des events ------------------
	validates :start_date, presence: true
	validate :cannot_change_the_past

	validates :duration, presence: true
	validate :multiple_of_5	

	validates :title, presence: true, length: { in: 5..140 }

	validates :description, presence: true, length: { in: 20..1000}

	validates :price, presence: true, numericality: { greather_than_or_equal_to: 0, less_than_or_equal_to: 1000 }

	validates :location, presence: true
	validate :has_picture

# Methode pour verifier la startdate de l'event,
# impossible de creer ou modifier un event passe.
def cannot_change_the_past
	if start_date.present? && start_date < Date.today
		errors.add(:start_date, "You can't change the past")
	end
end

# Methode pour verifier le format de la duree de l'event,
# impossible de creer sans que ce soit un multiple de 5.
def multiple_of_5

	if duration == 0 || duration % 5 != 0
		errors.add(:duration, "it must be a multiple of 5")
	end

end

# Méthode pour calculer la end_date de l'event.
def end_date
	start_date + duration * 60
end

def is_coming?(user)

	if self.attendances.where(user_id: user.id).count > 0
		return true
	else
		return false
	end
end

def has_picture
	if self.picture.attached? == false
		errors.add(:picture, "You must upload a picture")
	end
end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :is_admin, only: [:edit, :update, :destroy]
	before_action :is_validated, only: [:show]


	def index
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
		@event.save
		@event.picture.attach(params[:picture])


		if @event.save
			redirect_to root_path
			flash[:success] = "Your event has been successfully created"
		else
			flash.now[:error] = @event.errors.full_messages.to_sentence
			render :new
		end
	end

	def show
		@event = Event.find(params[:id])  	
	end

	def edit
		@event = Event.find(params[:id]) 
	end

	def update
		@event = Event.find(params[:id])
		
		if @event.update(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
			redirect_to event_path
			flash[:success] = "Your event has been successfully edited"
		else
			flash.now[:error] = @event.errors.full_messages.to_sentence
			render :edit
		end	
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to root_path
	end

	def is_admin
		@event = Event.find(params[:id])

		if current_user != @event.admin
			flash[:alert] = "You are not the organizer of this event"
			redirect_to event_path
		end

	end

	def has_picture
		if Event.picture.attached?
			return true
		else
			render 'new'
			flash[:alert] = "You must upload a picture"
		end
	end

	def is_validated
		@event = Event.find(params[:id])
		if @event.validated != true
			redirect_to root_path
			flash[:alert] = "Your event hasn't been validated"
		end
	end
end

app/controllers/gods/events_controller.rb
class Gods::EventsController < ApplicationController
	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

  def create
    @event = Event.new(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
    @event.save
    redirect_to gods_index_path
    flash[:success] = "The event has been created"
  end

  def edit
  	@event = Event.find(params[:id])
  end
	def update
		@event = Event.find(params[:id])
		@event.update(validated: params[:validated])
		if @event.update(validated: params[:validated]) && @event.validated == true
			UserMailer.event_validated_email(@event.admin, @event).deliver_now
		end
		redirect_to gods_events_path
	end
	


  def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to gods_events_path
	end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_banner.html.erb
<div class="jumbotron jumbotron-home">
  <div class="container">
  <h1 class="display-3 text-light">Live your best life!</h1>
  <p class="lead text-light">Never do nothing again </p>
  <hr class="my-4">
  <p class="text-light">Another super sentence to tell you how awesome our website is.</p>
  <p class="lead text-light">
    <%= link_to "Create your event", new_event_path, class:"btn btn-primary btn-lg" %>
  </p>
  </div>
</div>

app/views/events/_edit_event_form.html.erb
 <%= form_tag url_for(action: 'update'), method: "patch" do %>

    <b><%= label_tag 'Start date' %></b>
    <%= text_field_tag 'start_date', @event.start_date, class: "form-control" %>
    <small id="emailHelp" class="form-text text-muted mb-3">Ex: 2019-12-02 12:00</small>

    <b><%= label_tag 'Duration' %></b>
    <%= text_field_tag 'duration', @event.duration, class: "form-control", placeholder: "Minutes"  %>
    <small id="emailHelp" class="form-text text-muted mb-3">It must be a multiple of 5</small>

    <b><%= label_tag 'Title' %></b>
    <%= text_field_tag 'title', @event.title, class: "form-control"  %>
    <small id="emailHelp" class="form-text text-muted mb-3">Between 5 and 140 characters</small>

    <b><%= label_tag 'Description' %></b>
    <%= text_area_tag 'description', @event.description, class: "form-control"  %>
    <small id="emailHelp" class="form-text text-muted mb-3">Between 20 and 1000 characters</small>

    <b><%= label_tag 'Price' %></b>
    <%= text_field_tag 'price', @event.price, class: "form-control mb-3", placeholder: "€"  %>

    <b><%= label_tag 'Location' %></b>
    <%= text_field_tag 'location', @event.location, class: "form-control mb-3"  %>

    <p> <%= submit_tag "Edit", class: "btn btn-primary mb-3" %> <%= link_to 'Delete', event_path(id: @event), method: :delete, data: { confirm: 'Are you sure?' } %> </p>

<% end %>

app/views/events/_events_cards.html.erb
 <% events = Event.all.reverse %>
 
 <div class="container">
  <div class="row"> 
    <% events.each do |event|%>
    <% if event.validated == true %>
    <div class="col col-4 mb-4">
     <div class="card">
       <%= image_tag event.picture, style: 'height: 200px; width: 100%; display: block', alt: 'picture', class: "img-thumbnail mb-3 img-fluid"%>

       <div class="card-body">
        <h4 class="card-title"><%= event.title %></h4>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.start_date %><br>
          <%= event.location %></h6>
        <p class="card-text"><%= event.description %></p>
        <%= link_to "View details", event_path(event), class: "card-link" %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
</div>

app/views/events/_new_event_form.html.erb
<%= form_tag events_path, multipart: true do %>

<b><%= label_tag 'Start date' %></b>
<%= text_field_tag 'start_date', @event.start_date, class: "form-control datetimepicker-input" %>
<small id="emailHelp" class="form-text text-muted datetimepicker-input mb-3">Ex: 2019-12-02 12:00</small>

<b><%= label_tag 'Duration' %></b>
<%= text_field_tag 'duration', @event.duration, class: "form-control", placeholder: "Minutes"  %>
<small id="emailHelp" class="form-text text-muted mb-3">It must be a multiple of 5</small>

<b><%= label_tag 'Title' %></b>
<%= text_field_tag 'title', @event.title, class: "form-control"  %>
<small id="emailHelp" class="form-text text-muted mb-3">Between 5 and 140 characters</small>

<b><%= label_tag 'Description' %></b>
<%= text_area_tag 'description', @event.description, class: "form-control"  %>
<small id="emailHelp" class="form-text text-muted mb-3">Between 20 and 1000 characters</small>

<b><%= label_tag 'Price' %></b>
<%= text_field_tag 'price', @event.price, class: "form-control mb-3", placeholder: "€"  %>

<b><%= label_tag 'Location' %></b>
<%= text_field_tag 'location', @event.location, class: "form-control mb-3"  %>

<b><%= label_tag 'Event picture' %></b>
<%= file_field_tag :picture, class: "mb-3" %>

<%= submit_tag "Create", class: "btn btn-primary mb-4 mt-3" %>

<% end %>

app/views/events/_resource.html.erb
<div class="container mt-4">
 <div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-md-8 event-header">
      <%= image_tag @event.picture, alt: 'picture', class: "card-img" %>
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <p class="card-text"><small class="text-muted"><%= @event.start_date %></small></p>
        <h3 class="card-title"><%= @event.title %></h3>
        <p class="card-text"><%=@event.description%></p>
        <p class="card-text font-italic"><%= "Created by #{@event.admin.email}" %></p>
        <h4 class="card-text"><%= @event.price %> €</h4>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col col-md-8">
    <p class="event-icons"> <i class="fas fa-share-alt"></i>  <i class="fas fa-thumbs-up"></i></p>
  </div>
  <div class="col col-md-4">
    <% if current_user %>
    <% if @event.price > 0 %>
    <% unless @event.admin == current_user || @event.is_coming?(current_user) %>
    <p><%= link_to "Join this event", new_charge_path(id: @event.id), class: "btn btn-primary", role: "button" %></p>
    <% end %>

    <% else %>
    <% unless @event.admin == current_user || @event.is_coming?(current_user) %>
    <p><%= button_to 'Join free event', create_attendance_path(id: @event.id), class:"btn btn-success" %></p>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div>
<hr>

<div class="row mt-4">
  <div class="col col-md-8">
    <h5><%= @event.title %></h5>

    <div class="p text-justify">
      <%= @event.description %>
    </div>
</div>
    <div class="col col-md-4">
      <h5>Date and time</h5>
      <div class="p"><%= @event.start_date %> </div><br>
      
      <h5>ADDRESS</h5>
      <p><%= @event.location %></p>
      <h5>PEOPLE ATTENDING</h5>
      <p><%= @event.users.count %></p>
      

      <% if current_user %>
      <% if @event.admin == current_user %>
      <p><%= link_to "Your event", attendances_path(id: @event.id), class: "btn btn-primary", role: "button" %></p>
      <% end %>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col">
     <p class="event-icons"><i class="fab fa-twitter"></i> <i class="fab fa-facebook-square"></i> <i class="fab fa-instagram"></i></p>
   </div>
 </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col col-8 mx-auto mt-4">
      <h2>Edit your event</h2> 

      <%= render 'edit_event_form' %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<%= render 'banner' %>

<%= render partial: 'shared/events_cards', locals: {events: Event.all.reverse}%>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col col-8 mx-auto mt-4">
      <h2>Create your event</h2> 

      <%= render 'new_event_form' %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<%= render 'resource' %>