config/routes.rb
Rails.application.routes.draw do
  
  get 'attendances/index'
  get 'users/show'

  devise_for :users
  root to: 'events#index'


  resources :users do
    resources :avatars, only:[:create]
  end

  resources :events do
    resources :pictures, only:[:create]
  end

  
  resources :charges
  resources :attendances

  post 'create_attendance' => 'attendances#create', as: :create_attendance

 namespace :gods do
  get 'index'
  resources :users
  resources :events
  end
end

app/models/user.rb
class User < ApplicationRecord
	has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send 
	has_many :attendances
	has_many :events, through: :attendances

	# On crée une méthode qui appele la méthode welcome_email de UserMailer,
	# on passe en paramètre la classe user.
	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/gods/events_controller.rb
class Gods::EventsController < ApplicationController
	def index
		@events = Event.all
	end

	def show
		@event = Event.find(params[:id])
	end

	def new
		@event = Event.new
	end

  def create
    @event = Event.new(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
    @event.save
    redirect_to gods_index_path
    flash[:success] = "The event has been created"
  end

  def edit
  	@event = Event.find(params[:id])
  end
	def update
		@event = Event.find(params[:id])
		@event.update(validated: params[:validated])
		if @event.update(validated: params[:validated]) && @event.validated == true
			UserMailer.event_validated_email(@event.admin, @event).deliver_now
		end
		redirect_to gods_events_path
	end
	


  def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to gods_events_path
	end


end

app/controllers/gods/users_controller.rb
class Gods::UsersController < ApplicationController

	def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id]) 
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], password: params[:password], description: params[:description])
    @user.save
    redirect_to gods_index_path
    flash[:success] = "The user has been created"
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
      redirect_to gods_users_path
      flash[:success] = "The user has been updated"
    else
      flash[:alert] = "Something went wrong"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to gods_users_path
    flash[:success] = "The user has been deleted"
  end
end

app/controllers/gods_controller.rb
class GodsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_if_god
  def index
  end

  def check_if_god
  	if current_user.is_god == false 
  		flash[:alert] = "You shall not pass"
  		redirect_to root
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

  def show
  	dont_show
  	@user = User.find(params[:id])
  end

  def dont_show
  	@user = User.find(params[:id])
  	if @user != current_user
  		redirect_to root_path
  		flash[:alert] = "Condidential Information"
  	end
  end

  def edit
  	@user = User.find(params[:id])
  	redirect_to root_path, notice: "You can't edit this profile ma biche" unless current_user == @user
  end

  def update
  	@user = User.find(params[:id])
  	if current_user == @user
  		if @user.update(description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
  			redirect_to user_path 
  			flash[:success] = "Your profile has been successfully edited"
  		else 
  			flash[:alert] = "Try again"
  			render :edit
  		end
  	else
  		redirect_to root_path, notice: "You can't edit this profile ma biche"
  	end
  end
end

app/helpers/gods_helper.rb
module GodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gods/users/edit.html.erb
<div class="col col-6 mx-auto mt-4 text-dark">

      <h2>Edit user's information</h2>

      <!-- Zone du formulaire -->
      <%= form_tag url_for(action: 'update'), method: "patch", class: "mt-4" do %>

     <b> <%= label_tag 'Description' %></b>
      <%= text_field_tag 'description', @user.description, class: "form-control" %>
      <br />

      <b><%= label_tag 'First Name' %></b>
      <%= text_field_tag 'first_name', @user.first_name, class: "form-control"  %>
      <br />

      <b><%= label_tag 'Last Name' %></b>
      <%= text_field_tag 'last_name', @user.last_name, class: "form-control"  %>
      <br />

      <%= submit_tag "Edit", class: "btn btn-primary mb-3" %>

      <% end %>
</div>

app/views/gods/users/index.html.erb
<div class="col col-6 mx-auto">
<h2> Users </h2>
<p><%= link_to "Create a user", new_gods_user_path %></p>
<% @users.order(created_at: :asc).each do |u| %>
<p>
<%= "ID: #{u.id}" %><br>
<%= "Full name: #{u.first_name}" %>
<%= "#{u.last_name}" %> <br>
<%= "Email: #{u.email}" %> <br>
<%= "God: #{u.is_god}" %> <br>
<%= "Description: #{u.description}" %> <br>
<span> Events :</span> <br>
<% i = 1 %>
<% events = Event.where(admin_id: u.id) %>
	<% events.each do |e| %>
		<%="#{i}. #{e.title}" %><br>
		<% i += 1 %>
	<% end %>
	<%= link_to "Edit", edit_gods_user_path(u.id) %>
	<%= link_to 'Delete', gods_user_path(u.id), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<% end %> 
</div> 

app/views/gods/users/new.html.erb
<div class="text-dark">
  <h3 class="text-center mt-3 mb-4">Create user</h3> 

  <!-- Zone du formulaire -->
  <%= form_tag url_for(action: 'create'), method: 'post', class: "col col-4 mx-auto" do %>

  <b><%= label_tag 'First name' %></b>
  <%= text_field_tag 'first_name', @user.first_name, class: "form-control datetimepicker-input" %>


  <b><%= label_tag 'Last name' %></b>
  <%= text_field_tag 'last_name', @user.last_name, class: "form-control" %>


  <b><%= label_tag 'Email' %></b>
  <%= text_field_tag 'email', @user.email, class: "form-control"  %>
 

  <b><%= label_tag 'Password' %></b>
  <%= password_field_tag 'password', @user.password, class: "form-control"  %>

  <b><%= label_tag 'Description' %></b>
  <%= text_area_tag  'description',@user.description, class: "form-control mb-3"  %>

  <%= submit_tag "Create", class: "btn btn-primary mb-4 mt-3" %>

  <% end %>
</div>

<% if @user.errors.any? %>
<div class="alert alert-danger" role="alert">
 <p>The user can't be created for the reasons below:</p>
 <ul>
   <% @user.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>