config/routes.rb
Rails.application.routes.draw do
  
  get 'attendances/index'
  get 'users/show'

  devise_for :users
  root to: 'events#index'


  resources :users do
    resources :avatars, only:[:create]
  end

  resources :events do
    resources :pictures, only:[:create]
  end

  
  resources :charges
  resources :attendances

  post 'create_attendance' => 'attendances#create', as: :create_attendance

 namespace :gods do
  get 'index'
  resources :users
  resources :events
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :welcome_event
	belongs_to :user
	belongs_to :event

	# Méthode qui appelle la méthode event_welcome_email de UserMailer,
	# on lui passe en paramètre l'instance d'event que l'on retrouve grâce à son id.
	def welcome_event
		UserMailer.event_welcome_email(self.event, self.user).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord

	has_one_attached :picture
	has_many :attendances
	has_many :users, through: :attendances
	belongs_to :admin, class_name: "User"

	# --------------- Validates des events ------------------
	validates :start_date, presence: true
	validate :cannot_change_the_past

	validates :duration, presence: true
	validate :multiple_of_5	

	validates :title, presence: true, length: { in: 5..140 }

	validates :description, presence: true, length: { in: 20..1000}

	validates :price, presence: true, numericality: { greather_than_or_equal_to: 0, less_than_or_equal_to: 1000 }

	validates :location, presence: true
	validate :has_picture

# Methode pour verifier la startdate de l'event,
# impossible de creer ou modifier un event passe.
def cannot_change_the_past
	if start_date.present? && start_date < Date.today
		errors.add(:start_date, "You can't change the past")
	end
end

# Methode pour verifier le format de la duree de l'event,
# impossible de creer sans que ce soit un multiple de 5.
def multiple_of_5

	if duration == 0 || duration % 5 != 0
		errors.add(:duration, "it must be a multiple of 5")
	end

end

# Méthode pour calculer la end_date de l'event.
def end_date
	start_date + duration * 60
end

def is_coming?(user)

	if self.attendances.where(user_id: user.id).count > 0
		return true
	else
		return false
	end
end

def has_picture
	if self.picture.attached? == false
		errors.add(:picture, "You must upload a picture")
	end
end


end

app/models/user.rb
class User < ApplicationRecord
	has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	after_create :welcome_send 
	has_many :attendances
	has_many :events, through: :attendances

	# On crée une méthode qui appele la méthode welcome_email de UserMailer,
	# on passe en paramètre la classe user.
	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def after_sign_out_path_for(user)
		root_path		
	end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

	def index
		@event = Event.find(params[:id])
	end

	def new
	end

	def create
		@event = Event.find(params[:id])
		@attendance = Attendance.create(stripe_customer_id: "Free", user: current_user, event: @event)
		flash[:success] = "You joined the fucking event"
		redirect_to root_path
	end
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController

  def create
  	@user = User.find(params[:user_id])
  	@user.avatar.attach(params[:avatar])
  	redirect_to user_path(@user)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
        @event = Event.find(params[:id])
        @amount = @event.price
    end

    def create
        @event = Event.find(params[:id])
        @amount = @event.price * 100
      
      customer = Stripe::Customer.create({
        email: params[:stripeEmail],
        source: params[:stripeToken],
      })

      charge = Stripe::Charge.create({
        customer: customer.id,
        amount: @amount,
        description: 'Rails Stripe customer',
        currency: 'eur',
      })

      @attendance = Attendance.create(stripe_customer_id: customer.id, user: current_user, event: @event)
        redirect_to event_path(@event.id)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :is_admin, only: [:edit, :update, :destroy]
	before_action :is_validated, only: [:show]


	def index
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
		@event.save
		@event.picture.attach(params[:picture])


		if @event.save
			redirect_to root_path
			flash[:success] = "Your event has been successfully created"
		else
			flash.now[:error] = @event.errors.full_messages.to_sentence
			render :new
		end
	end

	def show
		@event = Event.find(params[:id])  	
	end

	def edit
		@event = Event.find(params[:id]) 
	end

	def update
		@event = Event.find(params[:id])
		
		if @event.update(admin: current_user, start_date: params[:start_date], duration: params[:duration], title: params[:title], description: params[:description], price: params[:price], location: params[:location])
			redirect_to event_path
			flash[:success] = "Your event has been successfully edited"
		else
			flash.now[:error] = @event.errors.full_messages.to_sentence
			render :edit
		end	
	end

	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to root_path
	end

	def is_admin
		@event = Event.find(params[:id])

		if current_user != @event.admin
			flash[:alert] = "You are not the organizer of this event"
			redirect_to event_path
		end

	end

	def has_picture
		if Event.picture.attached?
			return true
		else
			render 'new'
			flash[:alert] = "You must upload a picture"
		end
	end

	def is_validated
		@event = Event.find(params[:id])
		if @event.validated != true
			redirect_to root_path
			flash[:alert] = "Your event hasn't been validated"
		end
	end
end

app/controllers/gods_controller.rb
class GodsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_if_god
  def index
  end

  def check_if_god
  	if current_user.is_god == false 
  		flash[:alert] = "You shall not pass"
  		redirect_to root
  	end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def create
  	@event = Event.find(params[:event_id])
  	@event.pictures.attach(params[:picture])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show]

  def show
  	dont_show
  	@user = User.find(params[:id])
  end

  def dont_show
  	@user = User.find(params[:id])
  	if @user != current_user
  		redirect_to root_path
  		flash[:alert] = "Condidential Information"
  	end
  end

  def edit
  	@user = User.find(params[:id])
  	redirect_to root_path, notice: "You can't edit this profile ma biche" unless current_user == @user
  end

  def update
  	@user = User.find(params[:id])
  	if current_user == @user
  		if @user.update(description: params[:description], first_name: params[:first_name], last_name: params[:last_name])
  			redirect_to user_path 
  			flash[:success] = "Your profile has been successfully edited"
  		else 
  			flash[:alert] = "Try again"
  			render :edit
  		end
  	else
  		redirect_to root_path, notice: "You can't edit this profile ma biche"
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for_flash(type)
		case type
		when 'notice' then "alert-info"
		when 'success' then "alert-success"
		when 'error' then "alert-danger"
		when 'alert' then "alert-warning"
		end
	end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/gods_helper.rb
module GodsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_edit_form.html.erb
<%= form_tag url_for(action: 'update'), method: "patch", class: "mt-4" do %>

  <!-- First name -->
  <div class="form-group">
  <b><%= label_tag 'First Name' %></b>
  <%= text_field_tag 'first_name', @user.first_name, class: "form-control"  %>
  </div>

  <!-- Last name -->
  <div class="form-group">
  <b><%= label_tag 'Last Name' %></b>
  <%= text_field_tag 'last_name', @user.last_name, class: "form-control"  %>
  </div>

  <!-- Description -->
  <div class="form-group">
  <b><%= label_tag 'Description' %></b>
  <%= text_area_tag 'description', @user.description, class: "form-control" %>
  </div>

  <!-- Submit button -->
  <%= submit_tag "Edit", class: "btn btn-primary" %>

<% end %>    

app/views/layouts/_event_card.html.erb
 <% events = Event.all.reverse %>
 
 <div class="container">
  <div class="row"> 
    <% events.each do |event|%>
    <% if event.validated == true %>
    <div class="col col-4">
     <div class="card">
       <%= image_tag event.picture, style: 'height: 200px; width: 100%; display: block', alt: 'picture', class: "img-thumbnail mb-3 img-fluid"%>

       <div class="card-body">
        <h4 class="card-title"><%= event.title %></h4>
        <h6 class="card-subtitle mb-2 text-muted"><%= event.start_date %><br>
          <%= event.location %></h6>
        <p class="card-text"><%= event.description %></p>
        <%= link_to "View details", event_path(event), class: "card-link" %>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer class="footer py-3 bg-dark text-light mt-4">
    <div class="container">
      <div class="row">
        <div class="col col-8">
          <h6 class="text-light">About</h6>
          <p>Event-brite-like-like is an exercise made during The Hacking Project. Made in Lyon by 🦉 🦊.<br>
          Have a nice day!</p>
        </div>

        <div class="col col-4">
          <h6 class="text-light">Follow us</h6>
          <p>
            <i class="fab fa-twitter"></i> <i class="fab fa-facebook-square"></i> <i class="fab fa-instagram"></i>
          </p>
        </div>
      </div>
    </div>
  </footer>
  
<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Event Lyon</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- On met le favicon THP  -->
  <link rel="apple-touch-icon" sizes="180x180" href="https://www.thehackingproject.org/assets/favicon/apple-touch-icon-c01aaccf467f7cc3d79bbce743d60779f5b833fdc4500cebd07a5e11a07a5c31.png">
  <link rel="icon" type="image/png" sizes="32x32" href="https://www.thehackingproject.org/assets/favicon/favicon-32x32-804b12d1c41c60fe721477b7c3b0a32811dc610580dd40ac92f1cc04cbd05ca4.png">
  <link rel="icon" type="image/png" sizes="16x16" href="https://www.thehackingproject.org/assets/favicon/favicon-16x16-d96ba65e5785d32474df9ebc6fbfd5442c751d527b10981a474bc3b7a4079d01.png">

  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">


  <!-- Lien cdn de bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>

<div class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
   <%= link_to "Atomic Event", root_path, class: "navbar-brand" %> 
   <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="navbarResponsive" style="">
    <ul class="navbar-nav">
      <li class="nav-item">
       <%= link_to "Home", root_path, class: "nav-link" %>
     </li>
     <li class="nav-item">
      <%= link_to "New event", new_event_path, class: " nav-link" %>
    </li>
    <% if user_signed_in? %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Profile<span class="caret"></span></a>
      <div class="dropdown-menu">
        <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>

    <% else %>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" id="download">Sign up / Log in<span class="caret"></span></a>
      <div class="dropdown-menu">
        <%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Log In", new_user_session_path, class: "dropdown-item" %>
      </div>
      <% end %>
    </li>
    <% if user_signed_in? %>
    <% if current_user.is_god == true %>
    <li class="nav-item">
      <%= link_to "Dashboard", gods_index_path, class: "nav-link ml-3" %>
    </li>
    <%end%>
    <%end%>
  </ul>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/flash'%>

<%= yield %>

<%= render 'layouts/footer' %>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
	<!-- On met le favicon THP  -->
	<link rel="apple-touch-icon" sizes="180x180" href="https://www.thehackingproject.org/assets/favicon/apple-touch-icon-c01aaccf467f7cc3d79bbce743d60779f5b833fdc4500cebd07a5e11a07a5c31.png">
	<link rel="icon" type="image/png" sizes="32x32" href="https://www.thehackingproject.org/assets/favicon/favicon-32x32-804b12d1c41c60fe721477b7c3b0a32811dc610580dd40ac92f1cc04cbd05ca4.png">
	<link rel="icon" type="image/png" sizes="16x16" href="https://www.thehackingproject.org/assets/favicon/favicon-16x16-d96ba65e5785d32474df9ebc6fbfd5442c751d527b10981a474bc3b7a4079d01.png">

	<!-- Custom fonts for this template -->
	<link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">


	<!-- Lien cdn de bootstrap -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark navbar-custom">
		<%= link_to "Event Lyon", root_path, class: "navbar-brand" %>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<%= link_to "Home", root_path, class: "nav-item nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Create event", new_event_path, class: "nav-item nav-link" %>
				</li>

				<% if user_signed_in? %>
				<div class="dropdown ml-2">
					<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Profile
					</a>

					<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
						<%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
						<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
					</div>
				</div>

				<% else %>

				<div class="dropdown ml-2">
					<a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Sign Up / Sign In
					</a>

					<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
						<%= link_to "Sign Up", new_user_registration_path, class: "dropdown-item" %>
						<%= link_to "Sign In", new_user_session_path, class: "dropdown-item" %>
					</div>
				</div>
				<% end %>
			</li>
		</ul>
	</div>
</nav>
<%= yield %>

<!-- Footer -->
<footer class="py-5 bg-black">
	<div class="container">
		<p class="m-0 text-center text-white small">Made with 🦉 🦊 in Lyon - 2019</p>
	</div>
	<!-- /.container -->
</footer>

<!-- On appelle le Javascript de Bootstrap -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

app/views/shared/_city_card.html.erb
      <div class="col">
        <div class="card">
          <img style="height: 200px; width: 100%; display: block;" src="img/dj.jpg" alt="Card image">

          <div class="card-body">
            <h4 class="card-title">My Event</h4>
            <h6 class="card-subtitle mb-2 text-muted">2019/08/09 - Lyon</h6>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor reiciendis libero consectetur eum eius.</p>
            <a href="#" class="card-link">See event</a>
          </div>
        </div>
      </div>

      <div class="col">
        <div class="card">
          <img style="height: 200px; width: 100%; display: block;" src="img/cheers.jpg" alt="Card image">

          <div class="card-body">
            <h4 class="card-title">My Event</h4>
            <h6 class="card-subtitle mb-2 text-muted">2019/08/09 - Lyon</h6>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolor reiciendis libero consectetur eum eius.</p>
            <a href="#" class="card-link">See event</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- ATTENDEE CARDS -->
  
  <div class="container mt-4">
    <h2>City cards</h2>
    <div class="row"> 
      <div class="col">
        <div class="card overlay-container bg-dark text-white">
         <img class="card-img" src="img/lyon.jpg" alt="Card image">
         <div class="card-img-overlay">
          <div class="overlay-shadow"></div>
          <h2 class="card-title overlay-text">LYON</h2>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="card overlay-container bg-dark text-white">
       <img class="card-img h200" src="img/paris.jpg" alt="Card image">
       <div class="card-img-overlay">
        <div class="overlay-shadow"></div>
        <h2 class="card-title overlay-text">PARIS</h2>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card overlay-container bg-dark text-white">
     <img class="card-img" src="img/marseille.jpg" alt="Card image">
     <div class="card-img-overlay">
      <div class="overlay-shadow"></div>
      <h2 class="card-title overlay-text">MARSEILLE</h2>
    </div>
  </div>
</div>
</div>

app/views/shared/_elements.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Eventbrite Like-like</title>

  <!-- Link for bootstrap -->
  <link rel="stylesheet" href="styles/bootstrap.css" class="css">

  <!-- Custom stylesheet -->
  <link rel="stylesheet" href="styles/custom.css" class="css">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

</head>
<body>
    <div class="container">
    <div class="row mt-4">
      <div class="col">
        <small><a href="index.html">< Back to Menu</a></small>
        <h1>Element presentation page</h1>
      </div>
    </div>
  </div>

  <div class="container mt-4">
  <div class="row site-element align-items-center">
    <div class="col col-8">
      <img src="img/wine.jpg" alt="">
    </div>
    <div class="col col-4">
      <h4>Title</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga placeat cum enim distinctio fugit, obcaecati, tempore nostrum iusto aut molestiae, doloribus aliquid optio est velit eos neque hic, maiores mollitia.</p>
    <button type="button" class="btn btn-primary">Learn more</button>
    </div>
  </div>

  <div class="row site-element align-items-center mt-5">
    <div class="col col-8">
      <img src="img/cheers.jpg" alt="">
    </div>
  <div class="col col-4 order-first">
     <h4>Title</h4>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga placeat cum enim distinctio fugit, obcaecati, tempore nostrum iusto aut molestiae, doloribus aliquid optio est velit eos neque hic, maiores mollitia.</p>

      <button type="button" class="btn btn-primary">Learn more</button>
    </div>
    </div>
  </div>





 

<!--JAVASCRIPT -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


</body>
</html>

app/views/shared/_small_banner.html.erb
<div class="jumbotron jumbotron-events">
   <div class="container">
  <h1 class="display-4 text-light">Amazing events!</h1>
  </div>
</div>
 